package mini_c;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 11 13:35:52 MSK 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 25;
  public static final int SIZEOF = 12;
  public static final int CONTINUE = 31;
  public static final int SEMICOLON = 29;
  public static final int ELSE = 8;
  public static final int IDENT = 2;
  public static final int PLUS = 23;
  public static final int STRUCT = 6;
  public static final int INT = 5;
  public static final int EQUAL = 18;
  public static final int LP = 13;
  public static final int AMPAMP = 20;
  public static final int WHILE = 9;
  public static final int RP = 14;
  public static final int NOT = 28;
  public static final int RBRA = 16;
  public static final int RETURN = 11;
  public static final int IF = 7;
  public static final int LBRA = 15;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int CMP = 4;
  public static final int BREAK = 30;
  public static final int DIV = 26;
  public static final int BARBAR = 19;
  public static final int MINUS = 24;
  public static final int ARROW = 27;
  public static final int error = 1;
  public static final int EQ = 21;
  public static final int INTEGER = 3;
  public static final int FOR = 10;
  public static final int NEQ = 22;
  public static final int UMINUS = 32;
}

